theme: jekyll-theme-cayman
title: Funding the 2020 US Presidential Election
description: Some data analysis of the Federal Election Commission data on individual campaign contributions to Joe Biden and Donald Trump.
